/**   String   **/
var firstName = "Raja";
var schoolName = "ASR";
var collegeName = "JNTUH";
var subjectName = "Angular";
var higherStudeies = "MS";
var countryName = "India";
console.log("First Name:" + firstName);
console.log("School Name:" + schoolName);
console.log("College Name:" + collegeName);
console.log("Subject Name:" + subjectName);
console.log("Higher Studies:" + higherStudeies);
console.log("Country Name:" + countryName);
/***** Numbers ***/
var age = 24;
var price = 500.0;
var salary = 20000.00;
var weight = 78;
var marks = 45;
var mobileNumber = 9900990990;
var balance = 100000;
var id = 531;
var hike = 10;
var serialNumber = 1024;
var seatNumber = 25;
console.log("Age: " + age);
console.log("Price: " + price);
console.log("Palary: " + salary);
console.log("Weight: " + weight);
console.log("Marks: " + marks);
console.log("Mobile Number: " + mobileNumber);
console.log("Balance: " + balance);
console.log("Hike: " + hike);
console.log("SerialNumber: " + serialNumber);
console.log("SeatNumber: " + seatNumber);
/*** Booelan */
var isUserLogin = false;
var isEligible = true;
var isQualified = false;
var isWorking = true;
var isRich = true;
var isBlind = false;
var isMarried = false;
var isSingle = true;
var isCall = false;
var isPraise = true;
console.log("Is User Login: " + isUserLogin);
console.log("isEligible: " + isEligible);
console.log("isQualified: " + isQualified);
console.log("isWorking: " + isWorking);
console.log("isRich: " + isRich);
console.log("isBlind: " + isBlind);
console.log("isMarried: " + isMarried);
console.log("isSingle: " + isSingle);
console.log("isCall: " + isCall);
console.log("isPraise: " + isPraise);
/****** Array Examplesss  ********* */
var leapYears = [2020, 2040, 2050, 2090, 2045];
var myMarks = [35, 45, 67, 89, 78, 89];
var stockPrices = [0.989, 1.909, 0.88, 0.789];
var sensexVales = [59.00, 12.00, 1.11, 45, 88];
var companyNames = ["Infosys", "Wipro", "TCS", "Legato", "Cognizant"];
var subjects = ["Angualr", "HTML", "CSS", "Bootstrap", "JQuery"];
var experiences = [1, 5, 1.5, 6, 30, 23, 19];
var cities = ["HYD", "BAN", "CHE", "MUM", "DEL", "PUN"];
var toristPalces = ["TajMahal", "Charminar", "GateWay of India"];
var vehicleTypes = [2, 4, 3, 8, 6, 12];
console.log("Leap Years:" + leapYears);
console.log("myMarks:" + myMarks);
console.log("stockPrices:" + stockPrices);
console.log("sensexVales:" + sensexVales);
console.log("companyNames:" + companyNames);
console.log("subjects:" + subjects);
console.log("experiences:" + experiences);
console.log("cities:" + cities);
console.log("toristPalces:" + toristPalces);
console.log("vehicleTypes:" + vehicleTypes);
